// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { BackgroundGradientAnimation } from "@/components/ui/background-gradient-animation";
import { SidebarDemo } from "@/components/side";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-screen w-screen overflow-hidden")}>
        {/* Background layer */}
        <div className="fixed inset-0 -z-10">
          <BackgroundGradientAnimation />
        </div>

        {/* Foreground layer (sidebar + content) */}
        <div className="relative z-10 flex h-screen w-screen">
          <SidebarDemo />
          <main className="flex-1 overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
